apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ci-pipeline-app
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  destination:
    name: in-cluster
    namespace: default
  source:
    path: resources/ci-runtime/chart
    repoURL: https://github.com/Akshiv20/codefresh-training-app.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
      allowEmpty: false
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=false
      - ApplyOutOfSyncOnly=false
      - ServerSideApply=true
      - RespectIgnoreDifferences=false
