gitops-runtime:
  argo-workflows:
    controller:
      workflowDefaults:
        spec:
          archiveLogs: true
          artifactRepositoryRef:
            configMap: codefresh-workflows-log-store
            key: codefresh-workflows-log-store
  global:
    codefresh:
      accountId: 686fc6f0da2c64eef0d8fc4d
      userToken:
        secretKeyRef:
          name: codefresh-user-token
          key: token
    runtime:
      name: ci-runtime
      isConfigurationRuntime: false
